/**
 * Interactive OAuth2 credential setup
 * Automates the process of getting OAuth2 credentials from Google Cloud Console
 */

import readline from 'readline';
import open from 'open';
import { writeFile } from 'fs/promises';
import { fileExists } from '../utils/fs.js';

/**
 * Create readline interface for user input
 */
function createInterface() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
}

/**
 * Prompt user for input
 */
function question(rl, query) {
  return new Promise(resolve => rl.question(query, resolve));
}

/**
 * Interactive OAuth2 credential setup
 */
export async function interactiveOAuthSetup() {
  const rl = createInterface();

  console.log('\n🚀 Automated OAuth2 Credential Setup\n');
  console.log('This will guide you through creating OAuth2 credentials.');
  console.log('We\'ll open the browser for you - just follow the prompts!\n');

  try {
    // Step 1: Create/Select Project
    console.log('📁 Step 1: Create or Select a Google Cloud Project');
    console.log('   Opening browser to project creation page...\n');
    
    await open('https://console.cloud.google.com/projectcreate');
    
    await question(rl, '   ✓ Created/selected a project? Press Enter to continue... ');

    // Step 2: Configure OAuth Consent Screen
    console.log('\n🔐 Step 2: Configure OAuth Consent Screen');
    console.log('   Opening browser to OAuth consent screen...\n');
    
    await open('https://console.cloud.google.com/apis/credentials/consent');
    
    console.log('   Fill in the form:');
    console.log('   - User Type: External (unless you have Google Workspace)');
    console.log('   - App name: Auto Publisher');
    console.log('   - User support email: Your email');
    console.log('   - Developer contact: Your email');
    console.log('   - Click "Save and Continue"');
    console.log('   - Skip scopes (click "Save and Continue")');
    console.log('   - Add yourself as test user (if in testing mode)');
    console.log('   - Click "Save and Continue"\n');
    
    await question(rl, '   ✓ Completed OAuth consent screen? Press Enter to continue... ');

    // Step 3: Create OAuth Client ID
    console.log('\n🔑 Step 3: Create OAuth Client ID');
    console.log('   Opening browser to credentials page...\n');
    
    await open('https://console.cloud.google.com/apis/credentials');
    
    console.log('   Click "Create Credentials" → "OAuth client ID"');
    console.log('   - Application type: Desktop app');
    console.log('   - Name: Auto Publisher CLI');
    console.log('   - Click "Create"\n');
    console.log('   A popup will appear with your credentials.\n');

    // Step 4: Get Client ID
    console.log('📋 Step 4: Enter Your Credentials');
    console.log('   Copy the credentials from the popup:\n');
    
    const clientId = await question(rl, '   Client ID: ');
    
    if (!clientId || !clientId.includes('.apps.googleusercontent.com')) {
      console.error('\n❌ Invalid Client ID format. Should end with .apps.googleusercontent.com');
      rl.close();
      return false;
    }

    const clientSecret = await question(rl, '   Client Secret: ');
    
    if (!clientSecret || !clientSecret.startsWith('GOCSPX-')) {
      console.error('\n❌ Invalid Client Secret format. Should start with GOCSPX-');
      rl.close();
      return false;
    }

    // Step 5: Save credentials
    console.log('\n💾 Step 5: Saving Credentials...\n');
    
    const envContent = `# Google OAuth2 Credentials
# Generated by auto-publisher setup
GOOGLE_CLIENT_ID=${clientId}
GOOGLE_CLIENT_SECRET=${clientSecret}
`;

    await writeFile('.env', envContent, 'utf-8');
    
    console.log('✅ Credentials saved to .env file!');
    console.log('   File: .env (already in .gitignore)\n');

    rl.close();
    return true;

  } catch (error) {
    console.error('\n❌ Setup failed:', error.message);
    rl.close();
    return false;
  }
}

/**
 * Check if credentials are already set up
 */
export async function checkCredentialsSetup() {
  // Check for .env file
  if (await fileExists('.env')) {
    // Try to load it
    try {
      const dotenv = await import('dotenv');
      dotenv.config();
      
      if (process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET) {
        return true;
      }
    } catch (error) {
      // .env exists but might be invalid
    }
  }

  // Check environment variables
  if (process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET) {
    return true;
  }

  return false;
}

